CREATE OR REPLACE FUNCTION GET_ID_BANCO(NOME_ VARCHAR) RETURNS INT
AS $$
DECLARE
    TOTAL_LINHAS INTEGER;
    ID_BANCO_ INTEGER;
BEGIN
    -- Executa a consulta SELECT
    PERFORM * FROM BANCO WHERE NOME ILIKE NOME_;

    -- Obtém o número de linhas retornadas
    GET DIAGNOSTICS TOTAL_LINHAS = ROW_COUNT;

    IF (TOTAL_LINHAS = 0) THEN
        RAISE EXCEPTION 'NÃO FOI ENCONTRADO NENHUM BANCO COM ESSE NOME!';
    ELSIF (TOTAL_LINHAS > 1) THEN 
        RAISE EXCEPTION 'FOI ENCONTRADO MAIS DE BANCO COM COM ESSE NOME!';
    END IF;

    SELECT ID_BANCO INTO ID_BANCO_ FROM BANCO WHERE NOME ILIKE NOME_;
    RETURN ID_BANCO_;
END; $$ LANGUAGE PLPGSQL;