-- CRIANDO ROLES

CREATE ROLE admin;
CREATE ROLE gerente;
CREATE ROLE funcionario;
CREATE ROLE cliente;

-- GARANTINDO PERMISSOES PRO ADMIN (TODAS)

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA PUBLIC TO admin;

GRANT SELECT, INSERT ON SAQUEDEPOSITO TO gerente;
GRANT SELECT, INSERT ON TRANSFERENCIA TO gerente;
GRANT SELECT, INSERT ON FATURA TO gerente;
GRANT SELECT, INSERT ON COMPRAFATURA TO gerente;
GRANT SELECT, INSERT, UPDATE ON TABLE CLIENTE TO gerente;
GRANT SELECT, INSERT, UPDATE ON TABLE CONTA TO gerente;
GRANT SELECT, INSERT, UPDATE ON TABLE BANCO TO gerente;
GRANT SELECT, INSERT, UPDATE ON TABLE AGENCIA TO gerente;
GRANT SELECT, INSERT, UPDATE ON TABLE FUNCIONARIO TO gerente;
GRANT SELECT, INSERT, UPDATE ON TABLE CARTAO TO gerente;


-- GARANTINDO PERMISSOES PRO FUNCIONARIO 
GRANT SELECT ON SAQUEDEPOSITO TO funcionario;
GRANT SELECT ON TRANSFERENCIA TO funcionario;
GRANT SELECT ON FATURA TO funcionario;
GRANT SELECT ON COMPRAFATURA TO funcionario;

GRANT SELECT ON TABLE CLIENTE TO funcionario;
GRANT SELECT ON TABLE CONTA TO funcionario;
GRANT SELECT ON TABLE BANCO TO funcionario;
GRANT SELECT ON TABLE AGENCIA TO funcionario;
GRANT SELECT ON TABLE FUNCIONARIO TO funcionario;
GRANT SELECT ON TABLE CARTAO TO funcionario;

-- GARANTINDO PERMISSOES PRO CLIENTE (APENAS SELECIONAR)
GRANT EXECUTE ON FUNCTION extrato(ID_CONTA_BUSCADA INT, DT_INICIO DATE, DT_FIM DATE) TO cliente;
GRANT EXECUTE ON FUNCTION pagar_fatura(ID_FATURA INT) TO cliente;

-- Criar usuários
CREATE USER admin_user WITH PASSWORD 'senha_admin';
CREATE USER gerente_user WITH PASSWORD 'senha_gerente';
CREATE USER funcionario_user WITH PASSWORD 'senha_funcionario';
CREATE USER cliente_user WITH PASSWORD 'senha_cliente';

-- Atribuir papéis aos usuários
GRANT admin TO admin_user;
GRANT gerente TO gerente_user;
GRANT funcionario TO funcionario_user;
GRANT cliente TO cliente_user;