-- CRIANDO ROLES

CREATE ROLE admin;
CREATE ROLE gerente;
CREATE ROLE funcionario;
CREATE ROLE cliente;

-- GARANTINDO PERMISSOES PRO ADMIN (TODAS)

GRANT ALL PRIVILEGES ON ALL TABLES TO admin;

GRANT SELECT, INSERT ON SAQUEDEPOSITO TO gerente;
GRANT SELECT, INSERT ON TRANSFERENCIA TO gerente;
GRANT SELECT, INSERT ON FATURA TO gerente;
GRANT SELECT, INSERT ON COMPRAFATURA TO gerente;

-- GARANTINDO PERMISSOES PRO FUNCIONARIO ()
GRANT SELECT ON SAQUEDEPOSITO TO funcionario;
GRANT SELECT ON TRANSFERENCIA TO funcionario;
GRANT SELECT ON FATURA TO funcionario;
GRANT SELECT ON COMPRAFATURA TO funcionario;

-- GARANTINDO PERMISSOES PRO CLIENTE (APENAS SELECIONAR)
GRANT EXECUTE ON FUNCTION extrato(ID_CONTA_BUSCADA INT, DT_INICIO DATE, DT_FIM DATE) TO cliente;
GRANT EXECUTE ON FUNCTION pagar_fatura(ID_FATURA INT) TO cliente;

-- Criar usuários
CREATE USER admin_user WITH PASSWORD 'senha_admin';
CREATE USER gerente_user WITH PASSWORD 'senha_gerente';
CREATE USER funcionario_user WITH PASSWORD 'senha_funcionario';
CREATE USER cliente_user WITH PASSWORD 'senha_cliente';

-- Atribuir papéis aos usuários
GRANT admin TO admin_user;
GRANT gerente TO gerente_user;
GRANT funcionario TO funcionario_user;
GRANT cliente TO cliente_user;