CREATE TABLE
    FUNCIONARIO (
        MATRICULA SERIAL NOT NULL PRIMARY KEY,
        NOME VARCHAR(30) NOT NULL,
        SALARIO FLOAT NOT NULL,
        DATA_ULTIMA_ATUALIZACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        USUARIO_QUE_ATUALIZOU VARCHAR(30) NOT NULL DEFAULT CURRENT_USER,
        NUM_AGENCIA INT NOT NULL,
        FOREIGN KEY (NUM_AGENCIA) REFERENCES AGENCIA (NUM_AGENCIA)
    );

CREATE TABLE
    BANCO (
        ID_BANCO SERIAL PRIMARY KEY,
        NOME VARCHAR(30) NOT NULL,
    );

CREATE TABLE
    CLIENTE (
        ID_CLIENTE SERIAL NOT NULL PRIMARY KEY,
        CPF INTEGER NOT NULL,
        NOME VARCHAR(300) NOT NULL,
        ENDERECO TEXT NOT NULL,
        DT_NASC DATE NOT NULL,
        TELEFONE VARCHAR(11) NOT NULL
    );

CREATE OR REPLACE TABLE
    AGENCIA (
        NUM_AGENCIA SERIAL NOT NULL PRIMARY KEY,
        ID_BANCO INTEGER NOT NULL,
        ENDERECO TEXT,
        FOREIGN KEY (ID_BANCO) REFERENCES BANCO (ID_BANCO)
    );

CREATE TABLE
    CONTA (
        ID_CONTA SERIAL NOT NULL PRIMARY KEY,
        ID_CLIENTE INT NOT NULL,
        NUM_AGENCIA INT NOT NULL,
        SALDO FLOAT DEFAULT 0,
        IS_ACTIVE BOOLEAN DEFAULT TRUE,
        FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE),
        FOREIGN KEY (NUM_AGENCIA) REFERENCES AGENCIA (NUM_AGENCIA)
    );

CREATE TABLE
    TRANSFERENCIA (
        ID_TRANS SERIAL NOT NULL PRIMARY KEY,
        CONTA_ORIGEM INT NOT NULL,
        CONTA_DESTINO INT NOT NULL,
        VALOR FLOAT NOT NULL,
        DT_HR TIMESTAMP NOT NULL,
        FOREIGN KEY (CONTA_ORIGEM) REFERENCES CONTA (ID_CONTA),
        FOREIGN KEY (CONTA_DESTINO) REFERENCES CONTA (ID_CONTA)
    );

CREATE TABLE
    SAQUEDEPOSITO (
        ID_OPERACAO SERIAL NOT NULL PRIMARY KEY,
        CONTA_DESTINO INT NOT NULL,
        TIPO TEXT NOT NULL,
        VALOR FLOAT NOT NULL,
        DT_HR TIMESTAMP NOT NULL,
        FOREIGN KEY (CONTA_DESTINO) REFERENCES CONTA (ID_CONTA)
    );

CREATE TABLE
    CARTAO (
        NUM_CARTAO SERIAL NOT NULL PRIMARY KEY,
        ID_CONTA INT NOT NULL,
        DT_VAL TIMESTAMP NOT NULL,
        CVV INT NOT NULL,
        DT_ABERTURA TIMESTAMP NOT NULL,
        DT_FECHAMENTO TIMESTAMP NOT NULL,
        FOREIGN KEY (ID_CONTA) REFERENCES CONTA (ID_CONTA)
    );

CREATE TABLE
    FATURA (
        ID_FATURA SERIAL NOT NULL PRIMARY KEY,
        NUM_CARTAO INT NOT NULL,
        VALOR_TOTAL FLOAT NOT NULL,
        DT_VENCIMENTO TIMESTAMP NOT NULL,
        DT_FECHAMENTO TIMESTAMP NOT NULL,
        DT_PAG TIMESTAMP,
        MULTA FLOAT,
        FOREIGN KEY (NUM_CARTAO) REFERENCES CARTAO (NUM_CARTAO)
    );

CREATE TABLE
    COMPRACREDITO (
        ID_COMPRA SERIAL NOT NULL PRIMARY KEY,
        ID_CARTAO INT NOT NULL,
        VALOR_TOTAL FLOAT NOT NULL,
        DATA TIMESTAMP NOT NULL,
        QTD_PARCELAS INT NOT NULL,
        FOREIGN KEY (ID_CARTAO) REFERENCES CARTAO (ID_CARTAO)
    );

CREATE TABLE
    COMPRAFATURA (
        ID_COMPRAFATURA SERIAL NOT NULL PRIMARY KEY,
        ID_FATURA INT NOT NULL,
        ID_COMPRA INT NOT NULL,
        NUM_PARCELA INT NOT NULL,
        VALOR FLOAT NOT NULL,
        FOREIGN KEY (ID_FATURA) REFERENCES FATURA (ID_FATURA),
        FOREIGN KEY (ID_COMPRA) REFERENCES COMPRACREDITO (ID_COMPRA)
    )