CREATE OR REPLACE FUNCTION ATUALIZAR_LIMITE_E_FATURA() RETURNS TRIGGER AS 
$$ 
DECLARE 
	ID_CONTA_ INT;
BEGIN 
	SELECT ID_CONTA INTO ID_CONTA_ FROM COMPRAFATURA NATURAL JOIN FATURA NATURAL JOIN CARTAO NATURAL JOIN CONTA 
        WHERE ID_COMPRAFATURA = NEW.ID_COMPRAFATURA;

    UPDATE CONTA SET LIMITE = LIMITE - NEW.VALOR WHERE ID_CONTA = ID_CONTA_;

    UPDATE FATURA SET VALOR_TOTAL = VALOR_TOTAL + NEW.VALOR FROM CARTAO NATURAL JOIN CONTA 
        WHERE CARTAO.NUM_CARTAO = FATURA.NUM_CARTAO AND FATURA.ID_FATURA = NEW.ID_FATURA;
	
	RETURN NEW;
END; 
$$ LANGUAGE PLPGSQL;

CREATE OR REPLACE TRIGGER ATUALIZAR_LIMITE_E_FATURA_TR AFTER INSERT ON 
COMPRAFATURA FOR EACH ROW EXECUTE PROCEDURE ATUALIZAR_LIMITE_E_FATURA();

/* ------------------------------------------------------------------------------------------------------------------------------------------------------------------------ */