-- Updato
CREATE OR REPLACE FUNCTION VERIFICAR_UPDATE() RETURNS TRIGGER AS $$
BEGIN

    IF (NEW.SALDO < 0) THEN
        RAISE EXCEPTION 'O saldo da conta não pode ficar negativo!';
    END IF;

    RETURN NEW;
END;

$$ LANGUAGE PLPGSQL;

CREATE or REPLACE TRIGGER VERIFICAR_UPDATE_TR BEFORE UPDATE ON CONTA
EXECUTE PROCEDURE VERIFICAR_UPDATE();

-- Deleto
CREATE OR REPLACE FUNCTION NAO_PERMITIR_OPERACOES_CONTA() RETURNS TRIGGER AS $$
BEGIN
    IF(TG_OP = 'DELETE') THEN
        RAISE EXCEPTION "NÃO É PERMITIDO DELETAR SAQUES OU DEPÓSITOS"
    END IF;
    RETURN NEW;
END:
$$ LANGUAGE PGPLSQL;

CREATE TRIGGER VALIDATE_MUTATION BEFORE UPDATE OR DELETE ON CONTA FOR EACH ROW
EXECUTE PROCEDURE NAO_PERMITIR_OPERACOES_CONTA();