CREATE OR REPLACE FUNCTION VERIFICAR_UPDATE() RETURNS TRIGGER AS $$
BEGIN

    IF (NEW.SALDO < 0) THEN
        RAISE EXCEPTION 'O saldo da conta não pode ficar negativo!';
    END IF;

    RETURN NEW;
END;

$$ LANGUAGE PLPGSQL;

CREATE or REPLACE TRIGGER VERIFICAR_UPDATE_TR BEFORE UPDATE ON CONTA
EXECUTE PROCEDURE VERIFICAR_UPDATE();