CREATE OR REPLACE FUNCTION VALIDAR_FATURA() RETURNS TRIGGER AS 
$$ 
BEGIN 
	IF (TG_OP = 'INSERT') AND EXISTS(SELECT 1 FROM FATURA WHERE
		NUM_CARTAO=NEW.NUM_CARTAO AND DT_FECHAMENTO =
		NEW.DT_FECHAMENTO)
	THEN
		RAISE EXCEPTION 'FATURA JÁ EXISTE!';
	END IF;
	RETURN NEW;
	--ADICIONAR VALIDACAO PRA UPDATE TBM
END; 
$$ LANGUAGE PLPGSQL;

CREATE OR REPLACE TRIGGER VALIDAR_FATURA_TR BEFORE
INSERT OR UPDATE ON FATURA FOR EACH ROW
EXECUTE PROCEDURE VALIDAR_FATURA()

/* ----------------------------------------------------------------------- */


CREATE OR REPLACE FUNCTION FATURA_JA_FECHOU() RETURNS TRIGGER AS $$ 
	BEGIN 
		IF NEW.DT_PAGAMENTO != NULL AND DT_FECHAMENTO > CURRENT_DATE THEN
			RAISE EXCEPTION 'TENTATIVA DE PAGAR FATURA NÃO FECHADA!';
		END IF;
		RETURN NEW;
	END; $$ LANGUAGE PLPGSQL;
CREATE OR REPLACE TRIGGER FATURA_JA_FECHOU_TR BEFORE UPDATE ON FATURA FOR EACH ROW EXECUTE PROCEDURE FATURA_JA_FECHOU();