CREATE OR REPLACE FUNCTION NAO_PERMITIR_OPERACOES() RETURNS TRIGGER AS $$
BEGIN
    IF(TG_OP = 'DELETE') THEN
        RAISE EXCEPTION 'NÃO É PERMITIDO DELETAR SAQUES OU DEPÓSITOS';
    ELSIF (TG_OP = 'UPDATE') THEN
        RAISE EXCEPTION 'NÃO É PERMITIDO ATUALIZAR SAQUES OU DEPÓSITOS';
    END IF;
END;
$$ LANGUAGE PLPGSQL;
CREATE TRIGGER VALIDATE_MUTATION BEFORE UPDATE OR DELETE ON SAQUEDEPOSITO FOR EACH ROW
EXECUTE PROCEDURE NAO_PERMITIR_OPERACOES();

CREATE TRIGGER VALIDATE_MUTATION BEFORE UPDATE OR DELETE ON TRANSFERENCIA FOR EACH ROW
EXECUTE PROCEDURE NAO_PERMITIR_OPERACOES();