CREATE OR REPLACE FUNCTION GET_ID_CONTA(NOME_ VARCHAR) RETURNS INT
AS $$
DECLARE
    TOTAL_LINHAS INTEGER;
    ID_CONTA_ INTEGER;
BEGIN
    -- Executa a consulta SELECT
    PERFORM * FROM CONTA NATURAL JOIN CLIENTE WHERE NOME ILIKE NOME_;

    -- Obtém o número de linhas retornadas
    GET DIAGNOSTICS TOTAL_LINHAS = ROW_COUNT;

    IF (TOTAL_LINHAS = 0) THEN
        RAISE EXCEPTION 'NÃO FOI ENCONTRADO NENHUM USUÁRIO COM ESSE NOME!';
    ELSIF (TOTAL_LINHAS > 1) THEN 
        RAISE EXCEPTION 'FOI ENCONTRADO MAIS D EUM USUÁRIO COM ESSE NOME!';
    END IF;

    SELECT ID_CONTA INTO ID_CONTA FROM CONTA NATURAL JOIN CLIENTE WHERE NOME ILIKE NOME_;
    RETURN ID_CONTA_;
END; $$ LANGUAGE PLPGSQL;