-- FALTA VALIDAR SE A CONTA EXISTE, E SE NO CASO DO SAQUE EXISTE SALDO O SUFICIENTE
CREATE OR REPLACE FUNCTION SAQUEDEPOSITO(VALOR FLOAT, _ID_CONTA INT, TIPO INT) RETURNS VOID AS $$
BEGIN
    IF (VALOR <= 0) THEN
        RAISE EXCEPTION 'OBRIGATORIO PASSAGEM DE UM VALOR POSITIVO!';
    END IF;

    INSERT INTO SAQUEDEPOSITO VALUES(DEFAULT, _ID_CONTA, TIPO, VALOR, DEFAULT);
    
    IF (TIPO ILIKE 'S') THEN
        UPDATE CONTA SET SALDO = SALDO - VALOR WHERE ID_CONTA = _ID_CONTA;

    ELSIF (TIPO ILIKE 'D') THEN
        UPDATE CONTA SET SALDO = SALDO + VALOR WHERE ID_CONTA = _ID_CONTA;
    ELSE
        RAISE EXCEPTION 'OPERAÇÃO NÃO PERMITIDA!';
    END IF;

END;

$$ LANGUAGE PLPGSQL;


-- FALTA VALIDAR SE A CONTA EXISTE, E SE NO CASO DO SAQUE EXISTE SALDO O SUFICIENTE
CREATE OR REPLACE FUNCTION SAQUEDEPOSITO(VALOR FLOAT, NOME_CONTA INT, TIPO INT) RETURNS VOID AS $$
DECLARE 
    ID_CONTA_ INT;
BEGIN
    SELECT GET_ID_CONTA(NOME_ORIGEM) INTO ID_CONTA_;
    PERFORM SAQUEDEPOSITO(VALOR, ID_CONTA_, TIPO);
END;

$$ LANGUAGE PLPGSQL;