CREATE OR REPLACE FUNCTION DELETO(ID_CONTA_ TEXT) RETURNS VOID AS $$
BEGIN
    UPDATE CONTA SET IS_ACTIVE = FALSE WHERE ID_CLIENTE = ID_CONTA_;

    IF NOT FOUND THEN 
        RAISE EXCEPTION 'Conta com ID % não encontrado!', ID_CONTA_;
    END IF;
END;
$$ LANGUAGE PLPGSQL;

CREATE OR REPLACE FUNCTION DELETO(NOME_CLIENTE TEXT) RETURNS VOID AS $$
    DECLARE ID_CLIENTE_ INT;
BEGIN
    SELECT GET_ID_CONTA(NOME_CLIENTE) INTO ID_CLIENTE_;
    PERFORM DELETO(ID_CLIENTE_);
END;
$$ LANGUAGE PLPGSQL;