CREATE OR REPLACE FUNCTION ATUALIZAR(
    ID_CLIENTE_ INT,
    NOVO_NOME VARCHAR(300) DEFAULT NULL,
    NOVO_ENDERECO TEXT DEFAULT NULL,
    NOVA_DT_NASC DATE DEFAULT NULL,
    NOVO_TELEFONE VARCHAR(11) DEFAULT NULL
)
RETURNS VOID AS $$
BEGIN
    UPDATE CLIENTE
    SET 
        NOME = COALESCE(NOVO_NOME, NOME),
        ENDERECO = COALESCE(NOVO_ENDERECO, ENDERECO),
        DT_NASC = COALESCE(NOVA_DT_NASC, DT_NASC),
        TELEFONE = COALESCE(NOVO_TELEFONE, TELEFONE)
    WHERE 
        ID_CLIENTE = ID_CLIENTE_;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Cliente com ID % não encontrado', ID_CLIENTE;
    END IF;
END;
$$ LANGUAGE plpgsql;

--TODO: FAZER UMA PRA BANCO TBM?
