CREATE OR REPLACE FUNCTION VERIFICAR_LIMITE() RETURNS TRIGGER AS 
$$ 
DECLARE 
	LIMITE_ INT;
	DIA_FECHAMENTO_ INT;
	FATURA_JA_FECHOU_ BOOLEAN;
	EXISTE_FATURA_DESSE_MES_ BOOLEAN;
	EXISTE_FATURA_PROX_MES_ BOOLEAN;
	ID_FATURA_ INT;
BEGIN 

	SELECT LIMITE INTO LIMITE_ FROM CARTAO NATURAL JOIN CONTA WHERE NUM_CARTAO = NEW.NUM_CARTAO;
	
	IF LIMITE_ - NEW.VALOR_TOTAL < 0 THEN
		RAISE EXCEPTION 'LIMITE INSUFICIENTE PARA COMPRA!';
	END IF;
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
	SELECT DIA_FECHAMENTO INTO DIA_FECHAMENTO_ FROM CARTAO NATURAL JOIN CONTA WHERE NUM_CARTAO = NEW.NUM_CARTAO;
	SELECT EXISTS (SELECT 1 FROM FATURA WHERE DATE_TRUNC('month',DT_FECHAMENTO) = DATE_TRUNC('month',CURRENT_DATE) ) INTO EXISTE_FATURA_DESSE_MES_;
	SELECT EXISTS(SELECT 1 FROM FATURA WHERE DATE_TRUNC('month',DT_FECHAMENTO) = DATE_TRUNC('month',CURRENT_DATE+INTERVAL '1 month') ) INTO EXISTE_FATURA_PROX_MES_;
	SELECT (DIA_FECHAMENTO_ <= EXTRACT(DAY FROM CURRENT_DATE)) INTO FATURA_JA_FECHOU_;

	IF (FATURA_JA_FECHOU_) THEN
		-- RAISE EXCEPTION 'FATURA FECHADA';
		IF (NEW.QTD_PARCELAS > 1) THEN 
			FOR i IN 2..NEW.QTD_PARCELAS LOOP
				INSERT INTO FATURA( ID_FATURA, NUM_CARTAO, DT_FECHAMENTO) VALUES (
						DEFAULT,
						NEW.NUM_CARTAO,
						DATE_TRUNC('month',CURRENT_DATE) + make_interval(	months:= i, days := (DIA_FECHAMENTO_-1)));
			END LOPP;
		END IF;
		IF(EXISTE_FATURA_PROX_MES_) THEN
			SELECT ID_FATURA INTO ID_FATURA_ FROM FATURA WHERE DATE_TRUNC('month',DT_FECHAMENTO) = DATE_TRUNC('month',CURRENT_DATE+INTERVAL '1 month');
		ELSE 
				INSERT INTO FATURA( ID_FATURA, NUM_CARTAO, DT_FECHAMENTO) VALUES (
						DEFAULT,
						NEW.NUM_CARTAO,
						DATE_TRUNC('month',CURRENT_DATE+INTERVAL '1 month') + make_interval(days := (DIA_FECHAMENTO_-1)));
		END IF;
	
	ELSE
		-- RAISE EXCEPTION 'FATURA NAO FECHADA';

		IF (NEW.QTD_PARCELAS > 1) THEN 
			FOR i IN 2..NEW.QTD_PARCELAS LOOP
				INSERT INTO FATURA( ID_FATURA, NUM_CARTAO, DT_FECHAMENTO) VALUES (
						DEFAULT,
						NEW.NUM_CARTAO,
						DATE_TRUNC('month',CURRENT_DATE) + make_interval(	months:= i, days := (DIA_FECHAMENTO_-1)));
			END LOPP;
		END IF;

		IF(EXISTE_FATURA_DESSE_MES_) THEN
			SELECT ID_FATURA INTO ID_FATURA_ FROM FATURA WHERE DATE_TRUNC('month',DT_FECHAMENTO) = DATE_TRUNC('month',CURRENT_DATE);
		ELSE 
				INSERT INTO FATURA( ID_FATURA, NUM_CARTAO, DT_FECHAMENTO) VALUES (
						DEFAULT,
						NEW.NUM_CARTAO,
						DATE_TRUNC('month',CURRENT_DATE)+make_interval(days := (DIA_FECHAMENTO_-1)));
		END IF;
	
	
	END IF;

	RETURN NEW;
END; 
$$ LANGUAGE PLPGSQL;

CREATE OR REPLACE TRIGGER VERICAR_LIMITE_TR BEFORE INSERT ON 
COMPRACREDITO FOR EACH ROW EXECUTE PROCEDURE VERIFICAR_LIMITE();

CREATE OR REPLACE FUNCTION CRIAR_FATURA_PRA_PARCELA() RETURNS VOID AS $$ BEGIN

END;
$$ LANGUAGE PLPGSQL;
